### ISSUE TITLE
Product feed not working on multiple stores (linking to default Mage store)

### ISSUE THREAD

**Issue by stevengilroy** [mailchimp/mc-magento#442]
Magento 1.9.1.0
mc-magento 1.1.8

3 websites, with 1 store each attached.

Enabled in each website, rather than store, disabled in default config.

When adding products to an email in MC, the link is always the default store URL even when selecting one of the other stores in MC.

**Comment by MelissaEbizmarts** [comment]
Hello Steven, 
Please note that if you have a multi-store setup is best practice have a different list for each store.

Kind Regards.

**Comment by stevengilroy** [comment]
We do.

EBizmarts have looked into the config and it should be correct.

**Comment by stevengilroy** [comment]
Hi Melissa

We do. Pablo has looked into our configuration and has tried to fix it. He told me to raise the issue on GitHub.

Steve

**Comment by ebizmarts-keller** [comment]
Please try applying the following commit and if it solves the issue we would appreciate the feedback

https://github.com/mailchimp/mc-magento/commit/8837f9e23aebfb53a545453f60049264636cba57

**Comment by Poggen** [comment]
This does *not* resolve the issue. The product name is sent in the correct store scope, but the images still point to the default store url, which is really bad. We run 10-20 stores in each magento installation and keep the default store (on which we do all admin stuff) behind an ip address lock. Therefore, it is very important for us that the image urls sent to mailchimp reference the specific store url, since the API won't be able to access the images since they are behind the ip address lock if requested on the default store url.

**Comment by Santiagoebizmarts** [comment]
Hello,

Thanks for your feedback, image urls are handled differently than most of the data causing this.
We will get into this as soon as possible.

Thanks for your great feedback!
Regards.

**Comment by Santiagoebizmarts** [comment]
@Poggen 
This has been solved in the commit referenced above and will be available for next release.

Regards.

**Comment by Poggen** [comment]
I applied commit 2dd44d7 to my 1.1.9-installation, but it still didn't resolve the issue. It still sends image links pointing to our default magento store url to mailchimp.

**Comment by Santiagoebizmarts** [comment]
Hello,

The image is retrieved with the Magento store id, if that fails then there is probably a confict with another extension or the data in MailChimp remains with the old image url. Did you reset/resend the ecommerce data?

Regards.

**Comment by Poggen** [comment]
I've verified there's no conflict with other plugins and reset the store twice and tried sending the commerce data again to no avail. Image urls are still wrong (i.e. point to the main domain of the magento installation and not to store specific urls)

**Comment by Santiagoebizmarts** [comment]
Hello @Poggen ,

Maybe the image you are configuring are not the regular image of the products. Please note that by default the image sent is the one configured under the image field, not small_image nor thumbnail.

You can see the portion of code that retrieves the image [here](https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Helper/Data.php#L1041)

If you see any problem please let us know and we will do our best to fix it.
It does look okay for me as long as no extension conflicts with how the image are saved.

Kind Regards.

**Comment by Poggen** [comment]
I think you are misunderstanding the issue here. The image link generated is "correct" in the way that it points to the right image, however the link provided has the _wrong domain_. Instead of store-domain.com/path-to-image, the generated link is magento-admin-domain.com/path-to-image.

**Comment by Santiagoebizmarts** [comment]
Hello,

I see, probably the problem happens when calling the media URL without setting the store before.
I will re-open this issue. Thanks for helping us noticing this @Poggen 

Regards.

**Comment by Santiagoebizmarts** [comment]
The fix for this can be found at https://github.com/mailchimp/mc-magento/commit/f58e09d9fa53d3bb11eb3e8c6c9e223b2c3c63d9

Regards.
